In [1]:
import numpy as np

In [30]:
pwd

'C:\\Users\\ARPIT DUBEY\\Deep Learning'

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [5]:
#MEAN ABSOLUTE ERROR 
#without Using NUMPY
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [6]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [11]:
#POWER OF NUMPY
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [12]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [13]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [10]:
mae_np(y_predicted, y_true)

0.5

In [15]:
#LOG lOSS
#BINARY CROSSENTROPY



In [18]:
#log0 pe inf h so, hume ye check krna h ki eqn mai jha log h wha 0 as an input na jaaye!
np.log([0])

C:\Users\ARPIT DUBEY\AppData\Local\Temp\ipykernel_7888\690832447.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [17]:
epsilon = 1e-15

In [19]:
np.log([1e-15])

array([-34.53877639])

In [20]:
y_predicted

array([1, 1, 0, 0, 1])

In [21]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [22]:
1-epsilon

0.999999999999999

In [23]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [24]:
y_predicted_new = np.array(y_predicted_new)

In [25]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [26]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [27]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [29]:
log_loss(y_true, y_predicted)

17.2696280766844