In [1]:
import tensorflow as tf

In [16]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31] #in usdollar

#creating a tensorflow - dataset 
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [17]:
#this wud be in the tf format , so basically we need to convert it into numpy 
for sales in tf_dataset:
    print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [18]:
#1st approach
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [19]:
#2nd approach :- .take(3) function  selecting first 3 elts.
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [20]:
#as sale cant be in negative , so we need to filter it 

In [21]:
#.filter()
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [22]:
tf_dataset = tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [23]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2304
2232
2448
2232


In [25]:
#Doing batching !
#buffer_size =2 means batch of 2
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1512 1584]
[2304 2232]
[2448 2232]


In [27]:
#now in one line you can do this whole steps !

In [37]:
#data.Dataset will make this dataset into tensorflow format
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 2232]
[1512 2304]
[2448 2232]


In [33]:
images_ds = tf.data.Dataset.list_files(r"C:\Users\Ankit\Downloads\images\*\*\*", shuffle=False)

In [34]:
image_count = len(images_ds)
image_count

127

In [71]:
type(images_ds)

tensorflow.python.data.ops.shuffle_op._ShuffleDataset

In [76]:
def get_example():
    for file in images_ds.take(1):
        return file.numpy()
get_example()

b'C:\\Users\\Ankit\\Downloads\\images\\images\\dog\\100_ Dogs Pictures _ Download Free....jpg'

In [42]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'C:\\Users\\Ankit\\Downloads\\images\\images\\cat\\Why Do Cats Hate Water_ _ Britannica.jpg'
b'C:\\Users\\Ankit\\Downloads\\images\\images\\dog\\Genes contribute to dog breeds_ iconic....jpg'
b'C:\\Users\\Ankit\\Downloads\\images\\images\\cat\\The Joys of Owning a Cat - HelpGuide.org.jpg'


In [43]:
class_names = ["cat","dog"]

In [48]:
#This below is how we do training and testing dataset in DL tensorflow

In [49]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size) #.skip will skip the first 80%dataset

In [50]:
len(train_ds)

101

In [51]:
len(test_ds)

26

In [58]:
#example of splitting 
ankit = "images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg"
ankit.split('\\')

['images', 'dog', '20 Reasons Why Cats Make the Best Pets....jpg']

In [59]:
#now you can see that dog is at position 2nd from last 
ankit.split('\\')[-2]

'dog'

In [55]:
#this get_label will select from the string the word cat by splitting it with \\ 
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [54]:
get_label("images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [60]:
#the use of this get_label is to have a y , which is the target 

In [61]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [77]:
img, label = process_image(get_example())
img.numpy()[:2]

array([[[1.60054688e+02, 1.47171875e+02, 1.39921875e+02],
        [9.93398438e+01, 8.41835938e+01, 7.34062500e+01],
        [1.10589844e+02, 9.83242188e+01, 8.21953125e+01],
        [5.00234375e+01, 3.45781250e+01, 2.24257812e+01],
        [2.81562500e+01, 1.77851562e+01, 7.64843750e+00],
        [2.47500000e+01, 1.68945312e+01, 5.98046875e+00],
        [2.16445312e+01, 1.31679688e+01, 5.59375000e+00],
        [1.19414062e+01, 8.62890625e+00, 1.78515625e+00],
        [9.05859375e+00, 6.05859375e+00, 0.00000000e+00],
        [1.21367188e+01, 9.13671875e+00, 2.13671875e+00],
        [2.18320312e+01, 1.48320312e+01, 4.83203125e+00],
        [1.95859375e+01, 1.27421875e+01, 3.48437500e+00],
        [1.35312500e+01, 9.53125000e+00, 0.00000000e+00],
        [1.13203125e+01, 6.84375000e+00, 7.38281250e-01],
        [9.98046875e+00, 5.50390625e+00, 0.00000000e+00],
        [1.20039062e+01, 7.31640625e+00, 1.16015625e+00],
        [1.67382812e+01, 1.11562500e+01, 2.74218750e+00],
        [1.362

In [78]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [79]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[197.28906   206.28906   201.75781  ]
  [207.10156   209.80469   204.57031  ]
  [207.        208.46875   202.23438  ]
  ...
  [192.91028   186.91028   186.91028  ]
  [189.10156   180.10156   181.10156  ]
  [185.87732   176.87732   177.87732  ]]

 [[202.        207.        200.70312  ]
  [205.83069   205.83069   197.83069  ]
  [204.59375   203.70312   194.       ]
  ...
  [193.        187.        187.       ]
  [189.57031   185.57031   184.57031  ]
  [188.1554    179.1554    180.1554   ]]

 [[202.17188   202.        194.51562  ]
  [202.07385   202.07385   192.07385  ]
  [204.        204.        194.       ]
  ...
  [189.17188   183.17188   183.17188  ]
  [189.17188   183.17188   183.17188  ]
  [186.08997   180.08997   180.08997  ]]

 ...

 [[191.78528   189.7384    184.7384   ]
  [184.34229   179.34229   173.34229  ]
  [192.71875   190.57031   186.95312  ]
  ...
  [  0.         11.         31.       ]
  [  0.         11.         31.       ]
  [  0.         10.         

In [80]:
def scale(image, label):
    return image/255, label

In [83]:
train_ds = train_ds.map(scale)

In [84]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.00376024 0.00376586 0.0035975 ]
****Label:  b'dog'
****Image:  [0.002042   0.00273116 0.00346646]
****Label:  b'dog'
****Image:  [0.00033833 0.00033833 0.00033833]
****Label:  b'dog'
****Image:  [0.00267589 0.00266052 0.002599  ]
****Label:  b'cat'
****Image:  [0.00315948 0.00294418 0.0029288 ]
****Label:  b'dog'
